version: '2'

services:
  openfire:
    restart: always
    depends_on:
      - db
    build:
      context: ./openfire
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
      - "9090:9090"
      - "9091:9091"
    volumes:
      - '/var/openfire:/var/lib/openfire/conf'
  db:
    image: mysql:5.7.26
    ports:
      - "3305:3306"
    volumes:
      - '/var/mysql:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'openfire'