version: '2'

services:
  openfire1:
    restart: always
    depends_on:
      - db
      - beat
    image: abdurrahmanekr/openfire:4.4.2-apm
    pid: "host"
    ports:
      - "17070:7070"
      - "19090:9090"
    volumes:
      - 'openfire-data:/var/lib/openfire'
      - 'openfire-plugins:/usr/share/openfire/plugins'
      - 'openfire-lib:/usr/share/openfire-custom-libs'
    environment:
      APM_HOST: 'beat'
    networks:
      - apm

  openfire2:
    restart: always
    depends_on:
      - db
      - beat
    image: abdurrahmanekr/openfire:4.4.2-apm
    pid: "host"
    ports:
      - "17071:7070"
      - "19091:9090"
    volumes:
      - 'openfire-data:/var/lib/openfire'
      - 'openfire-plugins:/usr/share/openfire/plugins'
      - 'openfire-lib:/usr/share/openfire-custom-libs'
    environment:
      APM_HOST: 'beat'
    networks:
      - apm

  beat:
    image: docker.elastic.co/apm/apm-server:7.1.1
    ports:
      - "8200:8200"
      - "8201:8200"
    environment:
      - apm-server.host=0.0.0.0
    volumes:
      - ./apm-server.yml:/usr/share/apm-server/apm-server.yml
    networks:
      - apm
    depends_on:
      - elasticsearch
      - kibana

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - ELASTIC_PASSWORD=password
    networks:
      - apm
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    ports:
      - "5601:5601"
    networks:
      - apm
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD=password
    depends_on:
      - elasticsearch

  # DATABASE
  db:
    image: mysql:5.7.26
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - 'openfire-mysql:/var/lib/mysql'
      - 'openfire-mysql-log:/var/log/mysql'
    command: ["--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci", "--max_allowed_packet=132505856"]
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'openfire'
    networks:
      - apm

volumes:
  openfire-data:
  openfire-plugins:
  openfire-lib:
  openfire-mysql:
  openfire-mysql-log:

networks:
  apm:
    driver: bridge